### ISSUE TITLE
De verificat

### ISSUE THREAD

**Issue by emily222244** [portos060474/ticketing#5]
Buna, exista posibilitatea sa se combine anumite tickete intre ele? in sensul ca un ticket venit de la o adresa are in continut un e-mail venit de la altcineva. Am trimis pe e-mail cateva exemple. De verificat, te rog.

**Comment by emily222244** [comment]
Si o alta problema pe care am observat-o este ca pe suport_office vin ticketele fara fisierele atasate.Inclusiv cele assignate catre suport_office de catre alte departamente din firma (acolo, in sistemul de ticketing se vad).

**Comment by portos060474** [comment]
nu, nu exista
