### ISSUE TITLE
continut sters

### ISSUE THREAD

**Issue by emily222244** [portos060474/ticketing#6]
Buna,

Avem in continuare probleme cu continutul e-mailurilor, mai exact cu faptul ca in sistemul de ticketing apar goale (fara continut) desi persoana le trimite cu continut.
Vezi exemplu mai jos:

Pe suport-all apare asa:

"-----Original Message-----
From: Berdan Liliana [mailto:berdanliliana@yahoo.com] 
Sent: Tuesday, January 22, 2019 1:40 PM
To: suport_marketing@foreverliving.ro
Subject: Participare Raliu Stockholm

Buna ziua!

Pentru Raliu Stockholm, pt ID 407044, -Berdan Liliana!!
Biletul de avion îl voi achiziționa pentru data de 7 mai, cu întoarcere pe 12 mai!

Multumesc!
Liliana Berdan
Trimis de pe iPhone‑ul meu"

Iar in suport_marketing@foreverliving.ro apare asa:

"
From: suport_marketing@foreverliving.ro <suport_marketing@foreverliving.ro> 
Sent: Fără
To: cristi.istrati@foreverliving.ro
Subject: New [Ticket#570] has been created. Participare Raliu Stockholm

Ticket 570 has been created.
Click here to view the ticket and take action. 
berdanliliana@yahoo.com wrote:" 

si daca se intra in sistemul de ticketing, acest ticket nu are niciun continut.

Te rog verifica si poate reusesti sa faci ceva sa nu se mai stearga continutul e-mail-urilor .

Multumesc,
EMilia

**Comment by portos060474** [comment]
rezolvat
